spring:
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transport
    #big_event ???? ???
    #?????

server:
  port: 8091


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

